apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: progress42-ikea-demo-catalog
  description: FlyLo Air catalog for Progress42 IKEA workshop demo
spec:
  targets:
    - ./org.yaml
    - ./system.yaml
    - ./apis.yaml
    - ./components.yaml
