apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  namespace: flylo
  description: FlyLo Air platform engineering (demo)
spec:
  type: team
  profile:
    displayName: FlyLo Platform
    email: platform@flylo-air.example
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ops
  namespace: flylo
  description: FlyLo Air operations (demo)
spec:
  type: team
  profile:
    displayName: FlyLo Ops
    email: ops@flylo-air.example
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@flylo-air.example
  memberOf: [flylo/platform]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: emil
spec:
  profile:
    displayName: Emil Nildersen
    email: emil@progress42.example
  memberOf: [flylo/platform, flylo/ops]
