apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Progress42 platform team (demo)
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform@progress42.example
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: commerce-team
  description: Commerce / retail product team (demo)
spec:
  type: team
  profile:
    displayName: Commerce Team
    email: commerce@progress42.example
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@progress42.example
  memberOf: [platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: emil
spec:
  profile:
    displayName: Emil Nildersen
    email: emil@progress42.example
  memberOf: [platform-team, commerce-team]
