apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: flylo-air
  description: FlyLo Air airline digital platform (IKEA workshop demo)
  tags:
    - airline
    - flylo
    - demo
  links:
    - url: https://www.flylo-air.com/
      title: FlyLo Air website
      icon: catalog
    - url: https://backstage.progress42.com
      title: Backstage Demo
      icon: catalog
spec:
  owner: group:flylo/platform
